### ISSUE TITLE
Elasticsearch Scraper

### ISSUE THREAD

**Issue by AdamWang00** [FullStackAtBrownTeam/project-pantry-engine#3]
Create pipeline for scraping URL/ingredients from recipes on a given domain (e.g. tasty.co) and indexing the recipes into Elasticsearch. Refer to the Elasticsearch Python API docs and [our client Sami's repo](https://github.com/Sami-BG/recipe-browser) to get started.

**Comment by alexander-ding** [comment]
Just thinking out loud here: I think it's probably best to do the same inheritance pattern as Sami did, creating a parent Scraper class and implementing different variations for each website. Also, I think it's probably best to separate the indexing/elasticsearch stuff into a separate file. The Scraper can return a generator of recipe objects (maybe just a dict) that can we can index in some other logic.
